services:
  web:
    image: ${IMAGE_BASE}
    ports:
      - "13254:8080"
    environment:
      PROXY_URI: ${PROXY_URI}

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
