// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/mt5/ticks": {
            "post": {
                "description": "Accepts top-of-book quotes pushed by the MetaTrader 5 Expert Advisor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MT5"
                ],
                "summary": "Ingest MetaTrader 5 ticks",
                "parameters": [
                    {
                        "description": "Ticks",
                        "name": "ticks",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mt5.PushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mt5.PushResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/arbitrage": {
            "get": {
                "description": "Returns the latest calculated arbitrage opportunities",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Arbitrage"
                ],
                "summary": "Get arbitrage chains",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/arbitrage.ArbitrageChain"
                            }
                        }
                    }
                }
            }
        },
        "/backtest": {
            "get": {
                "description": "Simulates opening a position whenever the go leg clears min_entry and closing it when the net return on equity reaches target, reporting entries, exits, timeouts and profit or loss. Costs follow docs/trade-economics.md.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Replay recorded history as positions",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Chain path, repeatable; default every path with history",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Range start, unix seconds (default: 30 days ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Range end, unix seconds (default: now)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Bucket size in minutes: 1, 5, 15, 60, 240 or 1440 (default: auto)",
                        "name": "step",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Net return on equity that closes a position, percent (default 1)",
                        "name": "target",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Go-leg profit that opens a position, percent (default 1)",
                        "name": "min_entry",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Force-close after this many days (default 7)",
                        "name": "max_hold_days",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "K = 1/sum(margin) (default 0.83)",
                        "name": "capital_mult",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Financing on notional, percent per day (default 0.15)",
                        "name": "carry_per_day",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "One-off transfer cost per round trip, percent (default 0.04)",
                        "name": "transfer",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Share of profit taken per extension day, percent (default 0.5)",
                        "name": "profit_share_per_day",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Per-venue fee override as venue:fraction, repeatable",
                        "name": "fee",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include the per-trade list (default true)",
                        "name": "trades",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backtest.Result"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/balances": {
            "get": {
                "description": "Returns the latest wallet balances per price source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Balances"
                ],
                "summary": "Get wallet balances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/metrics.ExchangeBalances"
                            }
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "description": "Profit percentage per chain path in minute buckets (or coarser for long ranges)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Chain profit history",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Chain path, repeatable (max 10)",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Range start, unix seconds (default: 24h ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Range end, unix seconds (default: now)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Bucket size in minutes: 1, 5, 15, 60, 240 or 1440 (default: auto)",
                        "name": "step",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/history/paths": {
            "get": {
                "description": "Every arbitrage chain path that has recorded history, most recently seen first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Chain paths with history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/history.PathInfo"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orderbooks": {
            "get": {
                "description": "Returns all orderbooks from all exchanges",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orderbooks"
                ],
                "summary": "Get all orderbooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/orderbook.OrderBook"
                            }
                        }
                    }
                }
            }
        },
        "/orderbooks/{source}": {
            "get": {
                "description": "Returns all orderbooks for a specific price source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orderbooks"
                ],
                "summary": "Get orderbooks by source",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Price source name (e.g., kucoin, binance)",
                        "name": "source",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/orderbook.OrderBook"
                            }
                        }
                    }
                }
            }
        },
        "/orderbooks/{source}/{base}/{quote}": {
            "get": {
                "description": "Returns the orderbook for a specific price source, base and quote currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orderbooks"
                ],
                "summary": "Get specific orderbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Price source name (e.g., kucoin, binance)",
                        "name": "source",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base currency (e.g., BTC)",
                        "name": "base",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quote currency (e.g., USDT)",
                        "name": "quote",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderbook.OrderBook"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/overview": {
            "get": {
                "description": "Returns orderbooks, arbitrage chains, balances and stats in one payload",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dashboard overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Returns statistics about the orderbook store",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderbook.StoreStats"
                        }
                    }
                }
            }
        },
        "/up": {
            "get": {
                "description": "Check if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "arbitrage.ArbitrageChain": {
            "type": "object",
            "properties": {
                "end_amount": {
                    "type": "number"
                },
                "end_amount_no_fee": {
                    "description": "Without fee calculations",
                    "type": "number"
                },
                "end_currency": {
                    "type": "string"
                },
                "path": {
                    "description": "Human readable path like \"IRT -\u003e USDT (nobitex) -\u003e PAXG (binance) -\u003e GOLD18 (convert) -\u003e IRT (ecogold)\"",
                    "type": "string"
                },
                "profit_loss": {
                    "type": "number"
                },
                "profit_loss_no_fee": {
                    "type": "number"
                },
                "profit_percent": {
                    "type": "number"
                },
                "profit_percent_no_fee": {
                    "type": "number"
                },
                "start_amount": {
                    "type": "number"
                },
                "start_currency": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/arbitrage.ChainStep"
                    }
                }
            }
        },
        "arbitrage.ChainStep": {
            "type": "object",
            "properties": {
                "fixed_conversion": {
                    "$ref": "#/definitions/arbitrage.FixedConversionStep"
                },
                "trade": {
                    "$ref": "#/definitions/arbitrage.TradeStep"
                },
                "type": {
                    "description": "\"trade\" or \"conversion\"",
                    "type": "string"
                }
            }
        },
        "arbitrage.FixedConversionStep": {
            "type": "object",
            "properties": {
                "amount_in": {
                    "type": "number"
                },
                "amount_out": {
                    "type": "number"
                },
                "from": {
                    "type": "string"
                },
                "rate": {
                    "type": "number"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "arbitrage.TradeStep": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"buy\" or \"sell\"",
                    "type": "string"
                },
                "amount": {
                    "description": "amount of base currency",
                    "type": "number"
                },
                "amount_out": {
                    "description": "what we get after the trade (after fee)",
                    "type": "number"
                },
                "base": {
                    "type": "string"
                },
                "exchange": {
                    "$ref": "#/definitions/orderbook.PriceSourceName"
                },
                "fee_percent": {
                    "description": "trading fee as percentage (0.1 = 0.1%)",
                    "type": "number"
                },
                "price": {
                    "description": "effective price after orderbook depth",
                    "type": "number"
                },
                "quote": {
                    "type": "string"
                },
                "volume": {
                    "description": "volume in quote currency",
                    "type": "number"
                }
            }
        },
        "backtest.PairResult": {
            "type": "object",
            "properties": {
                "avg_hold_days": {
                    "type": "number"
                },
                "best_percent": {
                    "type": "number"
                },
                "entries": {
                    "description": "signals acted on",
                    "type": "integer"
                },
                "exits": {
                    "description": "reached the target",
                    "type": "integer"
                },
                "net_avg_percent": {
                    "type": "number"
                },
                "net_total_percent": {
                    "description": "sum of ROE over all closed trades",
                    "type": "number"
                },
                "no_exit_data": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "reverse_path": {
                    "type": "string"
                },
                "still_open": {
                    "description": "window runs past the end of the data",
                    "type": "integer"
                },
                "timeouts": {
                    "description": "force-closed at MaxHoldDays",
                    "type": "integer"
                },
                "trades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backtest.Trade"
                    }
                },
                "win_rate_percent": {
                    "description": "share of closed trades with ROE \u003e 0",
                    "type": "number"
                },
                "worst_percent": {
                    "type": "number"
                }
            }
        },
        "backtest.Params": {
            "type": "object",
            "properties": {
                "capital_mult": {
                    "description": "CapitalMult is K = 1/Σmᵢ, the notional-to-equity ratio.",
                    "type": "number"
                },
                "carry_per_day_percent": {
                    "description": "CarryPerDayPercent is Σcᵢ: financing on the whole notional, per day.",
                    "type": "number"
                },
                "fees": {
                    "description": "Fees maps a venue token to its per-hop trading fee as a fraction.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "max_hold_days": {
                    "description": "MaxHoldDays is how long a position may stay open before it is force-closed\nat whatever the return leg is worth.",
                    "type": "number"
                },
                "min_entry_percent": {
                    "description": "MinEntryPercent is the go-leg profit (after fees) that opens a position.",
                    "type": "number"
                },
                "profit_share_per_day_percent": {
                    "description": "ProfitSharePerDayPercent is taken out of a *profitable* position's return\nfor every day past the first (Nobitex charges 0.5%).",
                    "type": "number"
                },
                "target_percent": {
                    "description": "TargetPercent is the net return on equity a position must reach before it\nis closed.",
                    "type": "number"
                },
                "transfer_percent": {
                    "description": "TransferPercent is the one-off cost of moving capital, per round trip.",
                    "type": "number"
                }
            }
        },
        "backtest.Result": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "integer"
                },
                "exits": {
                    "type": "integer"
                },
                "from": {
                    "type": "integer"
                },
                "net_avg_percent": {
                    "type": "number"
                },
                "net_total_percent": {
                    "type": "number"
                },
                "no_exit_data": {
                    "type": "integer"
                },
                "pairs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backtest.PairResult"
                    }
                },
                "params": {
                    "$ref": "#/definitions/backtest.Params"
                },
                "step": {
                    "description": "Step is the bucket size in minutes the samples were read at. A backtest\ncan only see the spread at this resolution, so it bounds how precisely an\nexit can be timed.",
                    "type": "integer"
                },
                "still_open": {
                    "type": "integer"
                },
                "timeouts": {
                    "type": "integer"
                },
                "to": {
                    "type": "integer"
                },
                "win_rate_percent": {
                    "type": "number"
                }
            }
        },
        "backtest.Trade": {
            "type": "object",
            "properties": {
                "entry_percent": {
                    "description": "go leg, after fees",
                    "type": "number"
                },
                "entry_t": {
                    "type": "integer"
                },
                "exit_percent": {
                    "description": "return leg, after fees",
                    "type": "number"
                },
                "exit_t": {
                    "type": "integer"
                },
                "hold_days": {
                    "type": "number"
                },
                "net_roe_percent": {
                    "description": "after carry, transfer, profit share",
                    "type": "number"
                },
                "outcome": {
                    "type": "string"
                },
                "round_trip_percent": {
                    "description": "the two legs compounded",
                    "type": "number"
                }
            }
        },
        "history.PathInfo": {
            "type": "object",
            "properties": {
                "first_seen": {
                    "description": "unix seconds",
                    "type": "integer"
                },
                "last_seen": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "metrics.ExchangeBalances": {
            "type": "object",
            "properties": {
                "balances": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "exchange": {
                    "type": "string"
                },
                "last_fetched": {
                    "type": "string"
                }
            }
        },
        "mt5.PushRequest": {
            "type": "object",
            "properties": {
                "ticks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mt5.Tick"
                    }
                }
            }
        },
        "mt5.PushResult": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skipped": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "mt5.Tick": {
            "type": "object",
            "properties": {
                "ask": {
                    "type": "number"
                },
                "bid": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "time": {
                    "description": "Time is the broker's tick time in unix seconds. Optional: when absent or\nzero the server's own clock is used.",
                    "type": "integer"
                }
            }
        },
        "orderbook.OrderBook": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderbook.PriceLevel"
                    }
                },
                "base": {
                    "type": "string"
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderbook.PriceLevel"
                    }
                },
                "quote": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/orderbook.PriceSourceName"
                },
                "timestamp": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "orderbook.PriceLevel": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "orderbook.PriceSourceName": {
            "type": "string",
            "enum": [
                "binance",
                "kucoin",
                "ecogold",
                "nobitex",
                "mt5"
            ],
            "x-enum-varnames": [
                "PriceSourceBinance",
                "PriceSourceKucoin",
                "PriceSourceEcoGold",
                "PriceSourceNobitex",
                "PriceSourceMT5"
            ]
        },
        "orderbook.SourceStats": {
            "type": "object",
            "properties": {
                "orderbooks": {
                    "type": "integer"
                }
            }
        },
        "orderbook.StoreStats": {
            "type": "object",
            "properties": {
                "registered_sources": {
                    "type": "integer"
                },
                "source_stats": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/orderbook.SourceStats"
                    }
                },
                "total_orderbooks": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Arbi API",
	Description:      "Cryptocurrency Orderbook Aggregator API - Real-time orderbook data from multiple exchanges",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
