// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/orderbooks": {
            "get": {
                "description": "Returns all orderbooks from all exchanges",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orderbooks"
                ],
                "summary": "Get all orderbooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/orderbook.OrderBook"
                            }
                        }
                    }
                }
            }
        },
        "/orderbooks/{exchange}": {
            "get": {
                "description": "Returns all orderbooks for a specific exchange",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orderbooks"
                ],
                "summary": "Get orderbooks by exchange",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exchange name (e.g., kucoin)",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/orderbook.OrderBook"
                            }
                        }
                    }
                }
            }
        },
        "/orderbooks/{exchange}/{symbol}": {
            "get": {
                "description": "Returns the orderbook for a specific exchange and symbol",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orderbooks"
                ],
                "summary": "Get specific orderbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exchange name (e.g., kucoin)",
                        "name": "exchange",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Trading pair symbol (e.g., BTC-USDT)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderbook.OrderBook"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Returns statistics about the orderbook store",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderbook.StoreStats"
                        }
                    }
                }
            }
        },
        "/up": {
            "get": {
                "description": "Check if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "orderbook.OrderBook": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderbook.PriceLevel"
                    }
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderbook.PriceLevel"
                    }
                },
                "exchange": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "orderbook.PriceLevel": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "orderbook.SourceStats": {
            "type": "object",
            "properties": {
                "orderbooks": {
                    "type": "integer"
                }
            }
        },
        "orderbook.StoreStats": {
            "type": "object",
            "properties": {
                "registered_sources": {
                    "type": "integer"
                },
                "source_stats": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/orderbook.SourceStats"
                    }
                },
                "total_orderbooks": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Arbi API",
	Description:      "Cryptocurrency Orderbook Aggregator API - Real-time orderbook data from multiple exchanges",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
